import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, In } from 'typeorm';
import { Cron } from '@nestjs/schedule';
import { format } from 'date-fns';
import { Goal, GoalStatus } from '../entities/goal.entity';
import { Organization } from '../../organization/entities/organization.entity';
import { GoalTrackingService, GoalRiskAnalysis } from './goal-tracking.service';

interface GoalWithRisk {
  goal: Goal;
  risk: GoalRiskAnalysis;
}

interface GoalReviewData {
  organizationId: string;
  totalGoals: number;
  criticalGoals: GoalWithRisk[];
  highRiskGoals: GoalWithRisk[];
  onTrackGoals: GoalWithRisk[];
  reviewDate: Date;
}

@Injectable()
export class GoalReviewService {
  private readonly logger = new Logger(GoalReviewService.name);

  constructor(
    private readonly goalTrackingService: GoalTrackingService,
    @InjectRepository(Goal)
    private readonly goalRepo: Repository<Goal>,
    @InjectRepository(Organization)
    private readonly orgRepo: Repository<Organization>,
  ) {}

  /**
   * 주간 Goal 리뷰 (매주 금요일 17:00)
   */
  @Cron('0 17 * * 5') // 금요일 17:00
  async weeklyGoalReview(): Promise<void> {
    this.logger.log('Starting weekly goal review...');

    try {
      const organizations = await this.orgRepo.find();

      this.logger.log(
        `Running goal review for ${organizations.length} organizations`,
      );

      for (const org of organizations) {
        try {
          await this.runGoalReview(org.id);
        } catch (error) {
          const err = error as Error;
          this.logger.error(
            `Goal review failed for org ${org.id}: ${err.message}`,
            err.stack,
          );
        }
      }

      this.logger.log('Completed weekly goal review');
    } catch (error) {
      const err = error as Error;
      this.logger.error(
        `Failed to run weekly goal review: ${err.message}`,
        err.stack,
      );
    }
  }

  /**
   * Organization의 Goal 리뷰 실행
   */
  private async runGoalReview(organizationId: string): Promise<void> {
    const activeGoals = await this.goalRepo.find({
      where: {
        organizationId,
        status: In([GoalStatus.ACTIVE, GoalStatus.PAUSED]),
      },
      relations: ['ownerHollon', 'team'],
    });

    if (activeGoals.length === 0) {
      this.logger.log(`No active goals for organization ${organizationId}`);
      return;
    }

    // 리스크 분석
    const goalsWithRisk = await Promise.all(
      activeGoals.map(async (goal) => ({
        goal,
        risk: await this.goalTrackingService.analyzeGoalRisk(goal.id),
      })),
    );

    // 리스크 레벨별 분류
    const criticalGoals = goalsWithRisk.filter(
      (g) => g.risk.riskLevel === 'critical',
    );
    const highRiskGoals = goalsWithRisk.filter(
      (g) => g.risk.riskLevel === 'high',
    );
    const onTrackGoals = goalsWithRisk.filter(
      (g) => g.risk.riskLevel === 'low',
    );

    // 리뷰 문서 생성
    const reviewDocument = this.generateReviewDocument({
      organizationId,
      totalGoals: activeGoals.length,
      criticalGoals,
      highRiskGoals,
      onTrackGoals,
      reviewDate: new Date(),
    });

    // TODO: Document 저장 - DocumentService 구현 시 활성화
    // await this.documentService.create({
    //   organizationId,
    //   name: `Goal Review - ${format(new Date(), 'yyyy-MM-dd')}`,
    //   docType: 'meeting',
    //   scope: 'organization',
    //   scopeId: organizationId,
    //   content: reviewDocument,
    //   autoGenerated: true,
    //   keywords: ['goal', 'review', 'weekly', 'okr'],
    //   importance: 7,
    // });

    this.logger.log(
      `Goal review completed for organization ${organizationId}: ${criticalGoals.length} critical, ${highRiskGoals.length} high risk, ${onTrackGoals.length} on track`,
    );
    this.logger.debug(`Review document:\n${reviewDocument}`);

    // Critical Goal은 인간에게 알림 (향후 구현)
    if (criticalGoals.length > 0) {
      this.logger.warn(
        `Organization ${organizationId} has ${criticalGoals.length} critical goals requiring immediate attention`,
      );
      // TODO: await this.notifyHumans(organizationId, criticalGoals);
    }
  }

  /**
   * 리뷰 문서 생성
   */
  private generateReviewDocument(data: GoalReviewData): string {
    const {
      totalGoals,
      criticalGoals,
      highRiskGoals,
      onTrackGoals,
      reviewDate,
    } = data;

    return `# Weekly Goal Review - ${format(reviewDate, 'yyyy-MM-dd')}

## Executive Summary

- **Total Active Goals**: ${totalGoals}
- **Critical Risk**: ${criticalGoals.length} goals ⚠️
- **High Risk**: ${highRiskGoals.length} goals
- **On Track**: ${onTrackGoals.length} goals ✅

## Critical Goals (Immediate Action Required)

${
  criticalGoals.length === 0
    ? 'No critical goals at this time.\n'
    : criticalGoals
        .map(
          ({ goal, risk }) => `
### ${goal.title}

- **Progress**: ${goal.progressPercent.toFixed(1)}% (Expected: ${(risk.expectedProgress ?? 0).toFixed(1)}%)
- **Gap**: ${(risk.progressGap ?? 0).toFixed(1)}%
- **Remaining Days**: ${risk.remainingDays ?? 'N/A'}
- **Owner**: ${goal.ownerHollon?.name || 'Unassigned'}
- **Recommendation**: ${risk.recommendation}
`,
        )
        .join('\n')
}

## High Risk Goals

${
  highRiskGoals.length === 0
    ? 'No high risk goals at this time.\n'
    : highRiskGoals
        .map(
          ({ goal, risk }) => `
- **${goal.title}**: ${goal.progressPercent.toFixed(1)}% (Gap: ${(risk.progressGap ?? 0).toFixed(1)}%)
`,
        )
        .join('\n')
}

## On Track Goals

${
  onTrackGoals.length === 0
    ? 'No on-track goals at this time.\n'
    : onTrackGoals
        .slice(0, 5)
        .map(
          ({ goal }) => `
- **${goal.title}**: ${goal.progressPercent.toFixed(1)}%
`,
        )
        .join('\n')
}

${onTrackGoals.length > 5 ? `\n... and ${onTrackGoals.length - 5} more goals on track\n` : ''}

## Recommended Actions

${this.generateRecommendations(criticalGoals, highRiskGoals)}

---

*🤖 Generated automatically by GoalReviewService*
`;
  }

  /**
   * 권장 사항 생성
   */
  private generateRecommendations(
    criticalGoals: GoalWithRisk[],
    highRiskGoals: GoalWithRisk[],
  ): string {
    const recommendations: string[] = [];

    if (criticalGoals.length > 0) {
      recommendations.push(
        '1. **Address Critical Goals**: Schedule immediate review meetings for critical goals',
      );
    }

    if (highRiskGoals.length > 0) {
      recommendations.push(
        '2. **Rebalance Priorities**: Increase priority for high-risk goals',
      );
    }

    if (recommendations.length === 0) {
      recommendations.push(
        'All goals are on track. Continue current execution.',
      );
    }

    return recommendations.join('\n');
  }

  /**
   * 수동 Goal 리뷰 실행 (API로 호출 가능)
   */
  async runManualReview(organizationId: string): Promise<string> {
    await this.runGoalReview(organizationId);
    return 'Goal review completed successfully';
  }
}
