import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Knowledge Extraction Module - Create vector_embeddings table
 *
 * This migration:
 * - Enables pgvector extension for vector similarity search
 * - Creates the vector_embeddings table for storing embeddings of knowledge items
 * - Sets up indexes for efficient querying
 */
export class CreateVectorEmbeddingsTable1766557000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Enable pgvector extension
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS vector;`);

    // Create vector_embeddings table
    await queryRunner.query(`
      CREATE TABLE "vector_embeddings" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "knowledge_item_id" uuid NOT NULL,
        "embedding" vector NOT NULL,
        "dimension" integer NOT NULL,
        "model_version" varchar(100) NOT NULL,
        "metadata" jsonb,
        "created_at" timestamp NOT NULL DEFAULT now(),
        "updated_at" timestamp NOT NULL DEFAULT now(),
        CONSTRAINT "FK_vector_embeddings_knowledge_item"
          FOREIGN KEY ("knowledge_item_id")
          REFERENCES "knowledge_items"("id")
          ON DELETE CASCADE
      );
    `);

    // Create indexes for performance
    await queryRunner.query(`
      CREATE INDEX "idx_vector_embeddings_knowledge_item_id"
        ON "vector_embeddings"("knowledge_item_id");

      CREATE INDEX "idx_vector_embeddings_model_version"
        ON "vector_embeddings"("model_version");

      CREATE INDEX "idx_vector_embeddings_created_at"
        ON "vector_embeddings"("created_at");
    `);

    // Create vector similarity search index using HNSW (Hierarchical Navigable Small World)
    // This enables efficient approximate nearest neighbor search
    await queryRunner.query(`
      CREATE INDEX "idx_vector_embeddings_embedding_hnsw"
        ON "vector_embeddings"
        USING hnsw ("embedding" vector_cosine_ops);
    `);

    // Add comments for clarity
    await queryRunner.query(`
      COMMENT ON TABLE "vector_embeddings" IS
        'Stores vector embeddings for knowledge items to enable semantic search and similarity matching.
         Uses PostgreSQL pgvector extension for efficient vector operations.';

      COMMENT ON COLUMN "vector_embeddings"."knowledge_item_id" IS
        'Foreign key reference to the knowledge item this embedding represents.';

      COMMENT ON COLUMN "vector_embeddings"."embedding" IS
        'The vector embedding generated by the embedding model.';

      COMMENT ON COLUMN "vector_embeddings"."dimension" IS
        'The dimensionality of the embedding vector (e.g., 1536 for OpenAI text-embedding-3-small).';

      COMMENT ON COLUMN "vector_embeddings"."model_version" IS
        'Identifier for the embedding model version used to generate this vector.';

      COMMENT ON COLUMN "vector_embeddings"."metadata" IS
        'Additional metadata about the embedding generation process in JSON format.';
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Drop indexes
    await queryRunner.query(`
      DROP INDEX IF EXISTS "idx_vector_embeddings_embedding_hnsw";
      DROP INDEX IF EXISTS "idx_vector_embeddings_created_at";
      DROP INDEX IF EXISTS "idx_vector_embeddings_model_version";
      DROP INDEX IF EXISTS "idx_vector_embeddings_knowledge_item_id";
    `);

    // Drop table
    await queryRunner.query(`
      DROP TABLE IF EXISTS "vector_embeddings";
    `);

    // Note: We don't drop the vector extension as it might be used by other tables
    // If needed, it can be dropped manually with: DROP EXTENSION IF EXISTS vector;
  }
}
