import {
  Entity,
  Column,
  ManyToOne,
  OneToMany,
  JoinColumn,
  Index,
} from 'typeorm';
import { BaseEntity } from '../../../common/entities/base.entity';
import { Organization } from '../../organization/entities/organization.entity';
import { Team } from '../../team/entities/team.entity';
import { Hollon } from '../../hollon/entities/hollon.entity';
import { Project } from '../../project/entities/project.entity';
import { GoalProgressRecord } from './goal-progress-record.entity';

export enum GoalType {
  OBJECTIVE = 'objective',
  KEY_RESULT = 'key_result',
}

export enum GoalStatus {
  DRAFT = 'draft',
  ACTIVE = 'active',
  PAUSED = 'paused',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled',
  ARCHIVED = 'archived',
}

export enum GoalPriority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical',
}

export enum MetricType {
  BINARY = 'binary',
  NUMERIC = 'numeric',
  PERCENTAGE = 'percentage',
  CUSTOM = 'custom',
}

@Entity('goals')
@Index(['organizationId'])
@Index(['teamId'])
@Index(['parentGoalId'])
@Index(['status'])
@Index(['ownerHollonId'])
export class Goal extends BaseEntity {
  @Column({ name: 'organization_id' })
  organizationId: string;

  @Column({ name: 'team_id', nullable: true })
  teamId: string;

  @Column({ name: 'parent_goal_id', nullable: true })
  parentGoalId: string;

  // 목표 정보
  @Column({ length: 500 })
  title: string;

  @Column({ type: 'text', nullable: true })
  description: string;

  // OKR 타입
  @Column({
    name: 'goal_type',
    type: 'varchar',
    length: 20,
    default: GoalType.OBJECTIVE,
  })
  goalType: GoalType;

  // 상태
  @Column({
    type: 'varchar',
    length: 20,
    default: GoalStatus.DRAFT,
  })
  status: GoalStatus;

  // 진행도
  @Column({
    name: 'progress_percent',
    type: 'decimal',
    precision: 5,
    scale: 2,
    default: 0.0,
  })
  progressPercent: number;

  // 기간
  @Column({ name: 'start_date', type: 'date', nullable: true })
  startDate: Date;

  @Column({ name: 'target_date', type: 'date', nullable: true })
  targetDate: Date;

  @Column({
    name: 'completed_at',
    type: 'timestamp with time zone',
    nullable: true,
  })
  completedAt: Date;

  // 우선순위
  @Column({
    type: 'varchar',
    length: 20,
    default: GoalPriority.MEDIUM,
  })
  priority: GoalPriority;

  // 측정 기준 (Key Result용)
  @Column({ name: 'metric_type', type: 'varchar', length: 20, nullable: true })
  metricType: MetricType;

  @Column({
    name: 'target_value',
    type: 'decimal',
    precision: 15,
    scale: 4,
    nullable: true,
  })
  targetValue: number;

  @Column({
    name: 'current_value',
    type: 'decimal',
    precision: 15,
    scale: 4,
    default: 0,
  })
  currentValue: number;

  @Column({ length: 50, nullable: true })
  unit: string;

  // 성공 기준
  @Column({ name: 'success_criteria', type: 'jsonb', default: [] })
  successCriteria: string[];

  // 소유자
  @Column({ name: 'owner_hollon_id', nullable: true })
  ownerHollonId: string;

  // 자동 분해 관련
  @Column({ name: 'auto_decomposed', default: false })
  autoDecomposed: boolean;

  @Column({ name: 'decomposition_strategy', length: 50, nullable: true })
  decompositionStrategy: string;

  // 자율 생성 관련 (Phase 5+)
  @Column({ name: 'auto_generated', default: false })
  autoGenerated: boolean;

  @Column({ name: 'proposal_id', type: 'uuid', nullable: true })
  proposalId: string;

  @Column({ name: 'created_by_hollon_id', nullable: true })
  createdByHollonId: string;

  // Relations
  @ManyToOne(() => Organization, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'organization_id' })
  organization: Organization;

  @ManyToOne(() => Team, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'team_id' })
  team: Team;

  @ManyToOne(() => Goal, (goal) => goal.childGoals, {
    onDelete: 'SET NULL',
    nullable: true,
  })
  @JoinColumn({ name: 'parent_goal_id' })
  parentGoal: Goal;

  @OneToMany(() => Goal, (goal) => goal.parentGoal)
  childGoals: Goal[];

  @ManyToOne(() => Hollon, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'owner_hollon_id' })
  ownerHollon: Hollon;

  @ManyToOne(() => Hollon, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'created_by_hollon_id' })
  createdByHollon: Hollon;

  @OneToMany(() => Project, (project) => project.goal)
  projects: Project[];

  @OneToMany(() => GoalProgressRecord, (record) => record.goal)
  progressRecords: GoalProgressRecord[];
}
